# Generated by Django 5.1.2 on 2025-05-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
