# Generated by Django 5.1.2 on 2025-05-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
