# Generated by Django 5.1.2 on 2025-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_posts_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsposts',
            name='fk_tags',
            field=models.IntegerField(),
        ),
    ]
