# Generated by Django 5.1.2 on 2025-05-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('idbands', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bands',
                'verbose_name_plural': 'Bands',
                'db_table': 'Bands',
                'ordering': ['idbands'],
            },
        ),
        migrations.CreateModel(
            name='Feelings',
            fields=[
                ('idfeelings', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Feelings',
                'verbose_name_plural': 'Feelings',
                'db_table': 'Feelings',
                'ordering': ['idfeelings'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('idgenres', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genres',
                'verbose_name_plural': 'Genres',
                'db_table': 'Genres',
                'ordering': ['idgenres'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('idposts', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/')),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('songtitle', models.CharField(max_length=50)),
                ('album', models.CharField(blank=True, max_length=50, null=True)),
                ('band', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Posts',
                'db_table': 'Posts',
                'ordering': ['idposts'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('idtags', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
                'db_table': 'Tags',
                'ordering': ['idtags'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'ordering': ['idusers'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('idcomments', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fk_Posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posts')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
                'db_table': 'Comments',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TagsPosts',
            fields=[
                ('idtagsposts', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('fk_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posts')),
                ('fk_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tags')),
            ],
            options={
                'verbose_name': 'TagsPosts',
                'verbose_name_plural': 'TagsPosts',
                'db_table': 'TagsPosts',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='fk_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('idfollowers', models.AutoField(primary_key=True, serialize=False)),
                ('fk_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='app.users')),
                ('fk_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='app.users')),
            ],
            options={
                'verbose_name': 'Followers',
                'verbose_name_plural': 'Followers',
                'db_table': 'Followers',
                'ordering': ['idfollowers'],
            },
        ),
    ]
