# Generated by Django 5.1.2 on 2025-05-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_posts_options_alter_posts_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
